const MIN = { DESCRIPTION: 3, CATEGORY: 3, PRICE: 1 };

const TRANSACTION_COLLECTION_NAME = 'transactions';

const MAX_TRANSACTION_PER_PAGE = 10;

const AVAILABLE_PAGE_RAGES = {
  SMALL: 1,
  MEDIUM: 2,
  LARGE: 3,
  EXTRA_LARGE: 4,
} as const;

export const CONSTANTS = {
  MIN,
  TRANSACTION_COLLECTION_NAME,
  MAX_TRANSACTION_PER_PAGE,
  AVAILABLE_PAGE_RAGES,
};
